# Generated by Django 4.2.1 on 2023-05-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='diagnostico',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
